server:
  port: 8080
spring:
  application:
    name: gatling-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb # change to db<->localhost if you run container<->locally
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html